let councils = [
  {
    name: 'Arts and Humanities Research Council',
    short: 'AHRC',
    value: 'AHRC',
    index: 0,
  },
  {
    name: 'Biotechnology and Biological Sciences Research Council',
    short: 'BBSRC',
    value: 'BBSRC',
    index: 1,
  },
  {
    name: 'Economic and Social Research Council',
    short: 'ESRC',
    value: 'ESRC',
    index: 2,
  },
  {
    name: 'Engineering and Physical Sciences Research Council',
    short: 'EPSRC',
    value: 'EPSRC',
    index: 3,
  },
  {
    name: 'Innovate UK',
    short: '',
    value: 'Innovate UK',
    index: 4,
  },
  {
    name: 'Medical Research Council',
    short: 'MRC',
    value: 'MRC',
    index: 5,
  },
  {
    name: 'Natural Environment Research Council',
    short: 'NERC',
    value: 'NERC',
    index: 6,
  },
  {
    name: 'Research England',
    short: '',
    value: 'Research England',
    index: 7,
  },
  {
    name: 'Science and Technology Facilities Council',
    short: 'STFC',
    value: 'STFC',
    index: 8,
  },
  {
    name: 'UK Research and Innovation',
    short: 'UKRI',
    value: 'UKRI',
    index: 9,
  },
];

export const allCouncils = councils;

let ethical = [
  {
    name: 'Animals',
    index: 0,
  },
  {
    name: 'Human participants',
    index: 1,
  },
  {
    name: 'Stem cells',
    index: 2,
  },
  {
    name: 'Travel to hostile countries',
    index: 3,
  },
  {
    name: 'Work with developing/ODA countries ',
    index: 4,
  },
  {
    name: 'Responsible Innovation considerations',
    index: 5,
  },
  {
    name: 'Other',
    index: 6,
  },
  {
    name: 'Not applicable',
    index: 7,
  },
];
export const ethicalReasons = ethical;

let applicantTypes = [
  {
    name: 'Lead applicant',
    index: 0,
  },
  {
    name: 'Principal investigator',
    index: 1,
  },
  {
    name: 'Co-investigator',
    index: 2,
  },
  {
    name: 'Researcher',
    index: 3,
  },
  {
    name: 'Business partner',
    index: 4,
  },
  {
    name: 'Technician',
    index: 5,
  },
  {
    name: 'Fellow',
    index: 6,
  },
  {
    name: 'Student',
    index: 7,
  },
  {
    name: 'Admin staff',
    index: 8,
  },
];

export const allApplicantTypes = applicantTypes;

let allOrganisations = [
  {
    name: 'Lead applicant',
    index: 0,
  },
  {
    name: 'Principal investigator',
    index: 1,
  },
  {
    name: 'Co-investigator',
    index: 2,
  },
  {
    name: 'Researcher',
    index: 3,
  },
  {
    name: 'Business partner',
    index: 4,
  },
  {
    name: 'Technician',
    index: 5,
  },
  {
    name: 'Fellow',
    index: 6,
  },
  {
    name: 'Student',
    index: 7,
  },
  {
    name: 'Admin staff',
    index: 8,
  },
];

export const allOrgs = allOrganisations;

let allEductionalOrgs = [
  { name: 'Abertay University in Dundee' },
  { name: 'Aberystwyth University (Prifysgol Aberystwyth)' },
  { name: 'Anglia Ruskin University' },
  { name: 'Anglo-European College of Chiropractic' },
  { name: 'Archbishop of Canterbury, The' },
  { name: 'Arden University' },
  { name: 'Arts University Bournemouth' },
  { name: 'Ashridge Business School' },
  { name: 'Aston University' },
  { name: 'Bangor University (Prifysgol Bangor)' },
  { name: 'Bath Spa University' },
  { name: 'Birkbeck, London' },
  { name: 'Birmingham City University' },
  { name: 'Bishop Grossteste University' },
  { name: 'Blackpool and the Fylde College' },
  { name: 'Bournemouth University' },
  { name: 'BPP University' },
  { name: 'Brunel University London' },
  { name: 'Buckinghamshire New University' },
  { name: 'Canterbury Christ Church University' },
  { name: 'Cardiff Metropolitan University (Prifysgol Metropolitan Caerdydd)' },
  { name: 'Cardiff University (Prifysgol Caerdydd)' },
  { name: 'City University London' },
  { name: 'Cornwall College Group' },
  { name: 'Courtauld Institute of Art' },
  { name: 'Coventry University' },
  { name: 'Cranfield University' },
  { name: 'De Montfort University' },
  { name: 'Durham University' },
  { name: 'Edge Hill University' },
  { name: 'Edinburgh Napier University' },
  { name: 'Falmouth University' },
  { name: 'Foundation degrees' },
  { name: 'Glasgow Caledonian University' },
  { name: 'Glyndŵr University (Prifysgol Glyndŵr)' },
  { name: 'Goldsmiths, London' },
  { name: 'Grimsby Institute of Higher Education' },
  { name: 'Guildhall School of Music and Drama' },
  { name: 'Harper Adams University' },
  { name: 'Hartpury University' },
  { name: 'Heriot-Watt University' },
  { name: 'Heythrop College (degrees awarded by University of London)' },
  { name: 'Hull College' },
  { name: 'Imperial College of Science, Technology and Medicine' },
  { name: 'Institute of Cancer Research' },
  { name: 'Institute of Education, London' },
  { name: 'Keele University' },
  { name: 'King’s College London' },
  { name: 'Kingston University' },
  { name: 'Lancaster University' },
  { name: 'Leeds Arts University' },
  { name: 'Leeds Beckett University' },
  { name: 'Leeds City College' },
  { name: 'Leeds Trinity University' },
  { name: 'Liverpool Hope University' },
  { name: 'Liverpool John Moores University' },
  { name: 'Liverpool School of Tropical Medicine' },
  { name: 'London Business School' },
  { name: 'London Institute of Banking and Finance, The' },
  { name: 'London Metropolitan University' },
  { name: 'London School of Economics and Political Science, LSE' },
  { name: 'London School of Hygiene and Tropical Medicine' },
  { name: 'London South Bank University' },
  { name: 'Loughborough University' },
  { name: 'Manchester Metropolitan University' },
  { name: 'Middlesex University' },
  { name: 'NCG' },
  { name: 'New College Durham' },
  { name: 'Newcastle College' },
  { name: 'Newcastle University' },
  { name: 'Newman University, Birmingham' },
  { name: 'Northumbria University Newcastle' },
  { name: 'Norwich University of the Arts' },
  { name: 'Nottingham Trent University' },
  { name: 'Open University, The' },
  { name: 'Oxford Brookes University' },
  { name: 'Plymouth University' },
  { name: 'Queen Margaret University,Edinburgh' },
  { name: 'Queen Mary, London' },
  { name: 'Queen’s University Belfast' },
  { name: 'Ravensbourne' },
  { name: "Regent's University, London" },
  { name: 'Richmond, The American International University in London' },
  { name: 'Robert Gordon University, Aberdeen' },
  { name: 'Rose Bruford, College of Theatre and Performance' },
  { name: 'Royal Academy of Music' },
  { name: 'Royal Agricultural University' },
  { name: 'Royal Central School of Speech and Drama' },
  { name: 'Royal College of Art' },
  { name: 'Royal College of Music' },
  { name: 'Royal College of Nursing' },
  { name: 'Royal Conservatoire of Scotland' },
  { name: 'Royal Holloway, London' },
  { name: 'Royal Northern College of Music' },
  { name: 'Royal Veterinary College, The' },
  { name: 'School of Oriental and African Studies (SOAS), London' },
  { name: 'Sheffield Hallam University' },
  { name: 'Solent University' },
  { name: 'St George’s, London' },
  { name: 'St Mary’s University, Twickenham' },
  { name: 'Staffordshire University' },
  { name: 'Swansea University (Prifysgol Abertawe)' },
  { name: 'Teesside University' },
  { name: 'Trinity Laban Conservatoire of Music and Dance' },
  { name: 'University College Birmingham' },
  { name: 'University College London UCL' },
  { name: 'University College of Estate Management' },
  { name: 'University College of Osteopathy' },
  { name: 'University for the Creative Arts' },
  { name: 'University of Aberdeen' },
  { name: 'University of Bath' },
  { name: 'University of Bedfordshire' },
  { name: 'University of Birmingham' },
  { name: 'University of Bolton' },
  { name: 'University of Bradford' },
  { name: 'University of Brighton' },
  { name: 'University of Bristol' },
  { name: 'University of Buckingham' },
  { name: 'University of Cambridge' },
  { name: 'University of Central Lancashire' },
  { name: 'University of Chester' },
  { name: 'University of Chichester' },
  { name: 'University of Cumbria' },
  { name: 'University of Derby' },
  { name: 'University of Dundee' },
  { name: 'University of East Anglia, UEA' },
  { name: 'University of East London, UEL' },
  { name: 'University of Edinburgh' },
  { name: 'University of Essex' },
  { name: 'University of Exeter' },
  { name: 'University of Glasgow' },
  { name: 'University of Gloucestershire' },
  { name: 'University of Greenwich' },
  { name: 'University of Hertfordshire' },
  { name: 'University of Huddersfield' },
  { name: 'University of Hull' },
  { name: 'University of Kent' },
  { name: 'University of Law' },
  { name: 'University of Leeds' },
  { name: 'University of Leicester' },
  { name: 'University of Lincoln' },
  { name: 'University of Liverpool' },
  { name: 'University of London' },
  { name: 'University of Manchester' },
  { name: 'University of Northampton, The' },
  { name: 'University of Nottingham' },
  { name: 'University of Oxford' },
  { name: 'University of Portsmouth' },
  { name: 'University of Reading' },
  { name: 'University of Roehampton' },
  { name: 'University of Salford' },
  { name: 'University of Sheffield' },
  { name: 'University of South Wales (Prifysgol De Cymru)' },
  { name: 'University of Southampton' },
  { name: 'University of St Andrews' },
  { name: 'University of St Mark and St John, Plymouth' },
  { name: 'University of Stirling' },
  { name: 'University of Strathclyde' },
  { name: 'University of Suffolk' },
  { name: 'University of Sunderland' },
  { name: 'University of Surrey' },
  { name: 'University of Sussex' },
  { name: 'University of the Arts, London' },
  { name: 'University of the Highlands and Islands' },
  { name: 'University of the West of England, Bristol' },
  { name: 'University of the West of Scotland' },
  { name: 'University of Ulster' },
  { name: 'University of Wales (Prifysgol Cymru)' },
  { name: 'University of Wales Trinity Saint David (Prifysgol Cymru Y Drindod Dewi Sant)' },
  { name: 'University of Warwick' },
  { name: 'University of West London' },
  { name: 'University of Westminster' },
  { name: 'University of Winchester, The' },
  { name: 'University of Wolverhampton' },
  { name: 'University of Worcester' },
  { name: 'University of York' },
  { name: 'Warwickshire College' },
  { name: 'Writtle University College' },
  { name: 'York St John University' },
];

export const allOrgs2 = allEductionalOrgs;

let megaDataList = [
  {
    id: 'OPP124',
    name: 'UK-Canada Social Research Team Grants',
    funder: 'AHRC',
    org: 'University of Cardiff',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'overdue',
  },
  {
    id: 'OPP125',
    name: 'Strength in places Round 3',
    funder: 'EPSRC',
    org: 'Oxford University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP131',
    name: 'Public transport infrastructure development: tariff reduction and inter-connectivity Part III',
    funder: 'AHRC',
    org: 'Bristol University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP132',
    name: 'Responsive mode',
    funder: 'AHRC',
    org: 'University of Hardknocks',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP134',
    name: 'UK-Canada Diabetes Research Team Grants',
    funder: 'AHRC',
    org: 'Birmingham University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP135',
    name: 'UK social research for the next decade Part III',
    funder: 'Innovate UK',
    org: 'Swindon Polytechnic',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP137',
    name: 'Electric battery innovation for land-based travel',
    funder: 'AHRC',
    org: 'Imperial College London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP138',
    name: 'Entomophagy - acceptable levels of crunchiness for a post-apocalyptic world',
    funder: 'BBSRC',
    org: 'Queen Mary College',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'complete',
  },
  {
    id: 'OPP139',
    name: 'Salt-water gill adaptations in special transmorphogenic augementation',
    funder: 'MRC',
    org: 'King College, University of London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'complete',
  },
  {
    id: 'OPP140',
    name: 'Re-icing polar regions feasibility Part IV',
    funder: 'STFC',
    org: 'Newport University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP141',
    name: 'Reforestation and carbon capture',
    funder: 'NERC',
    org: 'East Anglia University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP143',
    name: 'Hydro-batteries and green energy storage in the environment',
    funder: 'AHRC',
    org: 'UWE, Bristol',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP145',
    name: 'Public transport infrastructure development: green power Part IV',
    funder: 'Research England',
    org: 'Fulchester University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP124',
    name: 'UK-Canada Social Research Team Grants',
    funder: 'AHRC',
    org: 'University of Cardiff',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'overdue',
  },
  {
    id: 'OPP125',
    name: 'Strength in places Round 3',
    funder: 'EPSRC',
    org: 'Oxford University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP131',
    name: 'Public transport infrastructure development: tariff reduction and inter-connectivity Part III',
    funder: 'AHRC',
    org: 'Bristol University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP132',
    name: 'Responsive mode',
    funder: 'AHRC',
    org: 'University of Hardknocks',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP134',
    name: 'UK-Canada Diabetes Research Team Grants',
    funder: 'AHRC',
    org: 'Birmingham University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP135',
    name: 'UK social research for the next decade Part III',
    funder: 'Innovate UK',
    org: 'Swindon Polytechnic',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP137',
    name: 'Electric battery innovation for land-based travel',
    funder: 'AHRC',
    org: 'Imperial College London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
];

export const megaData = megaDataList;

let megaDataAwardsList = [
  {
    id: 'OPP124',
    name: 'UK-Canada Social Research Team Grants',
    funder: 'MRC',
    org: 'University of Cardiff',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'overdue',
  },
  {
    id: 'OPP125',
    name: 'Strength in places Round 3',
    funder: 'EPSRC',
    org: 'Oxford University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP131',
    name: 'Public transport infrastructure development: tariff reduction and inter-connectivity Part III',
    funder: 'AHRC',
    org: 'Bristol University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP132',
    name: 'Responsive mode',
    funder: 'MRC',
    org: 'University of Hardknocks',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP134',
    name: 'UK-Canada Diabetes Research Team Grants',
    funder: 'MRC',
    org: 'Birmingham University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP135',
    name: 'UK social research for the next decade Part III',
    funder: 'Innovate UK',
    org: 'Swindon Polytechnic',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP137',
    name: 'Electric battery innovation for land-based travel',
    funder: 'MRC',
    org: 'Imperial College London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP138',
    name: 'Entomophagy - acceptable levels of crunchiness for a post-apocalyptic world',
    funder: 'MRC',
    org: 'Queen Mary College',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'complete',
  },
  {
    id: 'OPP139',
    name: 'Salt-water gill adaptations in special transmorphogenic augementation',
    funder: 'MRC',
    org: 'King College, University of London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'complete',
  },
  {
    id: 'OPP140',
    name: 'Re-icing polar regions feasibility Part IV',
    funder: 'STFC',
    org: 'Newport University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP141',
    name: 'Reforestation and carbon capture',
    funder: 'NERC',
    org: 'East Anglia University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP143',
    name: 'Hydro-batteries and green energy storage in the environment',
    funder: 'AHRC',
    org: 'UWE, Bristol',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP145',
    name: 'Public transport infrastructure development: green power Part IV',
    funder: 'Research England',
    org: 'Fulchester University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP124',
    name: 'UK-Canada Medical Research Team Grants',
    funder: 'MRC',
    org: 'University of Cardiff',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'overdue',
  },
  {
    id: 'OPP125',
    name: 'Strength in places Round 3',
    funder: 'EPSRC',
    org: 'Oxford University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
  {
    id: 'OPP131',
    name: 'Public transport infrastructure development: tariff reduction and inter-connectivity Part III',
    funder: 'AHRC',
    org: 'Bristol University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP132',
    name: 'Responsive mode',
    funder: 'MRC',
    org: 'University of Hardknocks',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP134',
    name: 'UK-Canada Diabetes Research Team Grants',
    funder: 'AHRC',
    org: 'Birmingham University',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'progress',
  },
  {
    id: 'OPP135',
    name: 'UK social research for the next decade Part III',
    funder: 'Innovate UK',
    org: 'Swindon Polytechnic',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'change',
  },
  {
    id: 'OPP137',
    name: 'Electric battery innovation for land-based travel',
    funder: 'AHRC',
    org: 'Imperial College London',
    numberOfAwards: '3',
    numberOfProjects: '12',
    awardAmount: '308,500',
    status: 'ready',
  },
];

export const megaDataAwards = megaDataAwardsList;

let megaDataApplicationsList = [
  {
    id: '97',
    name: 'Viral pandemic: distributed societal issues and news shaping',
    oppName: 'Electric battery innovation for land-based travel',
    funder: 'MRC',
    org: 'University of Cardiff',
    hoursLeft: '4',
    progressMessage: 'Deadline 4:00pm today',
    action: '',
    status: 'Ready to submit',
    completeness: '100% complete',
    active: true,
    imminent: true,
  },
  {
    id: '124',
    name: 'Viral pandemic: distributed societal issues and news shaping',
    oppName: 'Electric battery innovation for land-based travel',
    funder: 'MRC',
    org: 'University of Cardiff',
    daysLeft: '1',
    progressMessage: 'Deadline 21 Mar 2020',
    action: '',
    status: 'Ready to submit',
    completeness: '100% complete',
    active: true,
    imminent: true,
  },
  {
    id: '204',
    name: 'Recovery strategies from pollution in freshwater ecosystems',
    oppName: 'Freshwater ecology Part III, Where have all the invertebrates gone?',
    funder: 'NERC',
    org: 'Bath University',
    daysLeft: '34',
    progressMessage: 'Deadline 14 May 2020',
    action: '',
    status: 'In progress',
    completeness: '75% complete',
    active: true,
    imminent: false,
  },
  {
    id: '398',
    name: 'Effluent filtering in pre-treated brown water overflows',
    oppName: 'Freshwater ecology Part III, Where have all the invertebrates gone?',
    funder: 'NERC',
    org: 'Bath University',
    daysLeft: '34',
    progressMessage: 'Awaiting assessment',
    action: '',
    status: 'Submitted',
    completeness: '',
    active: true,
  },
  {
    id: '401',
    name: 'Jet propulsion systems in underwater environments',
    oppName: 'Freshwater ecology Part I, Sub aquatic travel and investigation methods?',
    funder: 'NERC',
    org: 'Abberllangeverybrewybethy University',
    daysLeft: '',
    progressMessage: 'Deadline 20 Jan 2020',
    finalMessage: 'Closed',
    action: '',
    status: 'Submitted',
    completeness: '',
    active: false,
  },
  {
    id: '417',
    name: 'Dimensional transmogrification methodology in domesticated urban felines.',
    oppName: 'Preservation of distributed and diverse avian populations in tendered and semi-wild non-rural environments',
    funder: 'NERC',
    org: 'Bristol University',
    daysLeft: '',
    progressMessage: 'Deadline 20 Jan 2020',
    finalMessage: 'Closed',
    action: 'Remove application',
    status: 'Not submitted',
    completeness: '',
    active: false,
  },
];
export const megaDataApplications = megaDataApplicationsList;
